Feature/auto release auto changelog implementation
Safe-Security/unleash-client pull request #10
Opened 2022-09-28 14:45 UTC by ANKDGIRI777

2022-09-29 07:37 UTC, aneeshrelan requested changes

2022-09-29 07:37 UTC, aneeshrelan commented on .github/workflows/release.yml
> +              run: npm install
Need to use `yarn` here to leverage our `yarn` cache file (`yarn.lock`)

2022-09-29 07:37 UTC, aneeshrelan commented on .github/workflows/release.yml
> +              run: npm run build
This will be `yarn build`

2022-09-29 07:37 UTC, aneeshrelan commented on .github/workflows/release.yml
> +              run: npm install --save-dev @semantic-release/changelog @semantic-release/git
We should add these ourselves in the `package.json`, again using `yarn` and remove this step altogether

2022-09-29 07:37 UTC, aneeshrelan commented on .github/workflows/release.yml
> +              run: npx semantic-release
For consistency sake, let's add a `release` script in package.json and have a simple `yarn release` here which internally runs `semantic-release`

2022-09-29 07:58 UTC, ANKDGIRI777 commented on .github/workflows/release.yml
> +              run: npm install
done

2022-09-29 07:58 UTC, ANKDGIRI777 commented on .github/workflows/release.yml
> +              run: npm run build
done

2022-09-29 07:58 UTC, ANKDGIRI777 commented on .github/workflows/release.yml
> +              run: npm install --save-dev @semantic-release/changelog @semantic-release/git
done

2022-09-29 07:58 UTC, ANKDGIRI777 commented on .github/workflows/release.yml
> +              run: npx semantic-release
done

2022-09-30 04:56 UTC, aneeshrelan requested changes

2022-09-30 04:56 UTC, aneeshrelan commented on package.json
> +        "typescript": "^4.8.3",
All these should move to `devDependencies`, only needed for development tasks

2022-09-30 04:56 UTC, aneeshrelan commented on package.json
> +        "release": "npx semantic-release"
If we have these in the dependencies, good to have without `npx` as well. Though internally `npx` will use the local module only if available. But in case not installed, `npx` installs the latest one that can have breaking changes. So, it's better to be explicit and only use local modules

2022-09-30 12:26 UTC, ANKDGIRI777 commented on package.json
> +        "typescript": "^4.8.3",
Done

2022-09-30 14:09 UTC, aneeshrelan approved these changes

2022-09-30 14:09 UTC, merged