Update Readme.md file & added type definition
Safe-Security/unleash-client pull request #7
Opened 2022-09-22 14:50 UTC by ANKDGIRI777

2022-09-22 14:55 UTC, prathap-safe requested changes

2022-09-22 14:55 UTC, prathap-safe commented on README.md
> +In order to solve this problem, the `Unleash` library used currently has been encapsulated in this package along with the desired defaults set up so that
This paragraph is not needed as the above covers it.

2022-09-22 14:55 UTC, prathap-safe commented on README.md
> +    baseUrl: "https://example.safescore.io",
Use publicly available values!

2022-09-22 14:56 UTC, prathap-safe commented
Update the PR title to match the actual changes made in the PR.

2022-09-23 05:15 UTC, ANKDGIRI777 commented on README.md
> +In order to solve this problem, the `Unleash` library used currently has been encapsulated in this package along with the desired defaults set up so that
Removed the paragraph

2022-09-23 05:16 UTC, ANKDGIRI777 commented on README.md
> +    baseUrl: "https://example.safescore.io",
Updated with publicly available values

2022-09-23 08:21 UTC, aneeshrelan approved these changes

2022-09-23 11:08 UTC, closed without merging